steps:
# Install PHP dependencies
- name: 'php:8.1-cli'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    composer install

# Install Node.js dependencies
- name: 'node:16'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    npm install

# PHP linting
- name: 'php:8.1-cli'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    vendor/bin/phpcs --standard=PSR12 src/

# JavaScript linting
- name: 'node:16'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    npm run lint

# PHP Unit Tests
- name: 'php:8.1-cli'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    vendor/bin/phpunit --configuration phpunit.xml

# JavaScript Tests
- name: 'node:16'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    npm test

# Build JavaScript assets
- name: 'node:16'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    npm run build

# Optional: Build and deploy PHP application
- name: 'php:8.1-cli'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    zip -r my-application.zip . -x "*.git*"

# Upload artifacts
artifacts:
  objects:
    location: 'gs://your-bucket/build-artifacts/'
    paths: ['**/my-application.zip', 'coverage/**', 'junit/report.xml']

timeout: '1200s'
